name: Ultimate Auto Claimer
on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * 4'

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run Background Claimer
        run: node epic-games
        env:
          EMAIL: ${{ secrets.EPIC_EMAIL }}
          PASSWORD: "63c15c30054643e39140fffac1325fa2"
